name: GriefPreventionBlockedCommands
main: com.bobcat00.griefpreventionblockedcommands.GriefPreventionBlockedCommands
version: ${project.version}
author: Bobcat00
depend: [GriefPrevention]
api-version: 1.15
